name: dr_libphonenumber
description: A starting point for Dart libraries or applications.
version: 0.0.1

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  ffi: ^2.0.2
  flutter_rust_bridge: ^1.78.0
  meta: ^1.9.1
  path: ^1.8.3
  pubspec_parse: ^1.2.3
  uuid: ^3.0.7
  # path: ^1.8.0

dev_dependencies:
  ffigen: ^8.0.2
  lints: ^2.0.0
  test: ^1.21.0
