// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.78.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';
import 'bridge_generated.dart';
export 'bridge_generated.dart';

class DrLibphonenumberPlatform
    extends FlutterRustBridgeBase<DrLibphonenumberWire>
    with FlutterRustBridgeSetupMixin {
  DrLibphonenumberPlatform(FutureOr<WasmModule> dylib)
      : super(DrLibphonenumberWire(dylib)) {
    setupMixinConstructor();
  }
  Future<void> setup() => inner.init;

// Section: api2wire

  @protected
  String api2wire_String(String raw) {
    return raw;
  }

  @protected
  Uint8List api2wire_uint_8_list(Uint8List raw) {
    return raw;
  }
// Section: finalizer
}

// Section: WASM wire module

@JS('wasm_bindgen')
external DrLibphonenumberWasmModule get wasmModule;

@JS()
@anonymous
class DrLibphonenumberWasmModule implements WasmModule {
  external Object /* Promise */ call([String? moduleName]);
  external DrLibphonenumberWasmModule bind(dynamic thisArg, String moduleName);
  external dynamic /* String */ wire_format(
      String phone_number, String iso_code, int phone_number_format);

  external dynamic /* int */ wire_get_number_type(
      String phone_number, String iso_code);

  external dynamic /* String */ wire_get_region_code_for_country_code(
      int calling_code);

  external dynamic /* List<dynamic> */ wire_get_region_info(
      String phone_number, String iso_code);

  external dynamic /* bool */ wire_is_valid_phone_number(
      String phone_number, String iso_code);
}

// Section: WASM wire connector

class DrLibphonenumberWire
    extends FlutterRustBridgeWasmWireBase<DrLibphonenumberWasmModule> {
  DrLibphonenumberWire(FutureOr<WasmModule> module)
      : super(WasmModule.cast<DrLibphonenumberWasmModule>(module));

  dynamic /* String */ wire_format(
          String phone_number, String iso_code, int phone_number_format) =>
      wasmModule.wire_format(phone_number, iso_code, phone_number_format);

  dynamic /* int */ wire_get_number_type(
          String phone_number, String iso_code) =>
      wasmModule.wire_get_number_type(phone_number, iso_code);

  dynamic /* String */ wire_get_region_code_for_country_code(
          int calling_code) =>
      wasmModule.wire_get_region_code_for_country_code(calling_code);

  dynamic /* List<dynamic> */ wire_get_region_info(
          String phone_number, String iso_code) =>
      wasmModule.wire_get_region_info(phone_number, iso_code);

  dynamic /* bool */ wire_is_valid_phone_number(
          String phone_number, String iso_code) =>
      wasmModule.wire_is_valid_phone_number(phone_number, iso_code);
}
