name: dr_libphonenumber
description: A new Flutter project.
version: 1.0.3
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  ffi: ^2.0.1
  equatable: ^2.0.3
  quiver: ^3.1.0
  package_config: ^2.1.0
  path: ^1.8.1
  dr_libphonenumber_platform_interface:
    git:
      url: https://github.com/TabooSun/dr_libphonenumber.git
      ref: v1.0.0-dr_libphonenumber_platform_interface
      path: dr_libphonenumber_platform_interface
  dr_libphonenumber_web:
    git:
      url: https://github.com/TabooSun/dr_libphonenumber.git
      ref: v1.0.0-dr_libphonenumber_web
      path: dr_libphonenumber_web

dev_dependencies:
  taboosun_lints:
    git:
      url: https://github.com/TabooSun/dart_taboosun_lints.git
      ref: v1.1.3
  flutter_test:
    sdk: flutter
  ffigen: ^6.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.tech_creator.dr_libphonenumber.dr_libphonenumber
        pluginClass: DrLibphonenumberPlugin
      ios:
        pluginClass: DrLibphonenumberPlugin
      macos:
        pluginClass: DrLibphonenumberPlugin
      web:
        default_package: dr_libphonenumber_web

scripts:
  copy_test_runner: cp test/dr_libphonenumber_test_runner.dart example/integration_test/.